Default: &defaults
  database: haskell-photos-gallery.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: haskell-photos-gallery_test.sqlite3
  <<: *defaults

Staging:
  database: haskell-photos-gallery_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: haskell-photos-gallery_production.sqlite3
  poolsize: 100
  <<: *defaults
